// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/6/2026, 4:29:55 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/christianhuber/webdev/plantoria/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christianhuber/webdev/plantoria/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christianhuber/webdev/plantoria/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christianhuber/webdev/plantoria/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christianhuber/webdev/plantoria/src/plugins/**/*.{js,ts,mjs}","/Users/christianhuber/webdev/plantoria/src/composables/**/*.{js,ts,mjs}","/Users/christianhuber/webdev/plantoria/src/utils/**/*.{js,ts,mjs}","/Users/christianhuber/webdev/plantoria/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/christianhuber/webdev/plantoria/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/christianhuber/webdev/plantoria/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/christianhuber/webdev/plantoria/src/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;